services:
  postgres:
    image: "postgres:16.3"
    environment:
      POSTGRES_DB: "some-database"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "super-secret"
    ports:
      - "5432:5432"
